"""
Layer-4 Analysis Schemas.
Defines the strict types for Threat Assessment and Reporting.
"""
from enum import Enum
from dataclasses import dataclass
from typing import List, Optional

class ThreatLevel(Enum):
    LOW = "LOW"
    GUARDED = "GUARDED"
    ELEVATED = "ELEVATED"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    ANOMALY = "ANOMALY"


@dataclass
class Hypothesis:
    """
    A hypothesis produced by a minister.
    Encapsulates predicted signals, matched observations, and causal coverage.
    """
    minister: str
    predicted_signals: List[str]
    matched_signals: List[str]
    missing_signals: List[str]
    coverage: float = 0.0
    dimension: str = "UNKNOWN"
    confidence: float = 0.0
    weight: float = 1.0  # FIX-2: Bayesian weight — never destroyed, only adjusted

    def __post_init__(self) -> None:
        # Compatibility: allow legacy callers to pass confidence-only semantics.
        try:
            cov = float(self.coverage or 0.0)
        except Exception:
            cov = 0.0

        try:
            legacy = float(self.confidence or 0.0)
        except Exception:
            legacy = 0.0

        self.coverage = max(0.0, min(1.0, cov if cov > 0.0 else legacy))
        self.confidence = self.coverage
        self.dimension = str(self.dimension or "UNKNOWN").strip().upper()
        self.weight = max(0.01, float(self.weight or 1.0))
    

@dataclass
class AssessmentReport:
    """
    The formal intelligence product generated by the Council.
    """
    threat_level: ThreatLevel
    confidence_score: float  # 0.0 - 1.0 (Grounded Confidence)
    summary: str
    key_indicators: List[str]
    missing_information: List[str]
    recommendation: str
    
    # Metadata
    minister_consensus: float = 0.0
    synthesis_logic: str = ""
    timestamp: str = ""
