"""
STIX 2.1 Intelligence Export (NEW — DIP 2.1)

Converts DIP assessment results into STIX 2.1 JSON bundles for
interoperability with the broader cyber threat intelligence (CTI)
ecosystem — MISP, OpenCTI, ThreatConnect, etc.

STIX 2.1 objects produced:
  - Report (the overall assessment)
  - Indicator (each signal as an observable pattern)
  - ThreatActor (country/entity under assessment)
  - Relationship (links signals → assessment)
  - Identity (DIP 2.0 system identity)

References:
  - STIX 2.1 spec: https://docs.oasis-open.org/cti/stix/v2.1/
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

try:
    from stix2 import (
        Bundle, Indicator, Relationship, Report, ThreatActor, Identity,
    )
    HAS_STIX2 = True
except Exception:
    HAS_STIX2 = False


DIP_IDENTITY_ID = f"identity--{uuid.uuid4()}"
DIP_IDENTITY_BASE = {
    "type": "identity",
    "spec_version": "2.1",
    "created": "2025-01-01T00:00:00.000Z",
    "modified": "2025-01-01T00:00:00.000Z",
    "name": "Politiq AI — Geopolitical Intelligence Engine",
    "identity_class": "system",
    "sectors": ["intelligence", "defense"],
}

# Domain → STIX pattern mapping
DOMAIN_PATTERNS = {
    "military": "[military-activity:activity_type = '{}']",
    "diplomatic": "[diplomatic-activity:activity_type = '{}']",
    "economic": "[economic-activity:activity_type = '{}']",
    "cyber": "[cyber-activity:activity_type = '{}']",
    "political": "[political-activity:activity_type = '{}']",
    "information": "[information-activity:activity_type = '{}']",
}


def export_stix_bundle(
    result: Dict[str, Any],
    session: Any = None,
) -> Optional[Dict[str, Any]]:
    """
    Export an assessment result as a STIX 2.1 Bundle.

    Returns a JSON-serializable dict (the STIX bundle) or None if stix2
    is not installed.
    """
    if not HAS_STIX2:
        return _generate_stix_fallback(result)

    objects: List[Any] = []
    now = datetime.now(timezone.utc)

    # ── Identity (DIP 2.0 system) ──
    system_id = f"identity--{uuid.uuid4()}"
    dip_identity = Identity(
        id=system_id,
        created="2025-01-01T00:00:00.000Z",
        modified=now,
        name="Politiq AI — Geopolitical Intelligence Engine",
        identity_class="system",
        sectors=["intelligence", "defense"],
    )
    objects.append(dip_identity)

    # ── Threat Actor (assessed country/entity) ──
    country = result.get("country", "UNKNOWN")
    threat_actor_id = f"threat-actor--{uuid.uuid4()}"
    threat_actor = ThreatActor(
        id=threat_actor_id,
        created=now,
        modified=now,
        name=f"Geopolitical Entity: {country}",
        threat_actor_types=["nation-state"],
        sophistication="strategic",
        resource_level="government",
    )
    objects.append(threat_actor)

    # ── Indicators (signals) ──
    indicator_ids: List[str] = []
    sre_data = result.get("nextgen_sre", {}) or {}
    projected_signals = sre_data.get("projected_signals", []) or []

    for i, signal in enumerate(projected_signals[:20]):
        sig_name = signal if isinstance(signal, str) else str(signal)
        domain = _infer_domain(sig_name)
        pattern = DOMAIN_PATTERNS.get(domain, DOMAIN_PATTERNS["political"]).format(
            sig_name.replace("'", "\\'")
        )

        indicator = Indicator(
            id=f"indicator--{uuid.uuid4()}",
            created=now,
            modified=now,
            name=f"Signal: {sig_name[:80]}",
            description=f"Geopolitical signal detected for {country}: {sig_name}",
            pattern=pattern,
            pattern_type="stix",
            valid_from=now,
            indicator_types=["anomalous-activity"],
        )
        objects.append(indicator)
        indicator_ids.append(indicator.id)

    # ── Report (the assessment) ──
    threat_level = result.get("threat_level", "UNKNOWN")
    trace_id = result.get("trace_id", str(uuid.uuid4())[:12])

    report = Report(
        id=f"report--{uuid.uuid4()}",
        created=now,
        modified=now,
        name=f"Politiq AI Assessment: {country} — {threat_level}",
        description=(
            f"Geopolitical intelligence assessment for {country}. "
            f"Threat level: {threat_level}. "
            f"Trace ID: {trace_id}. "
            f"Generated by Politiq AI Strategic Risk Engine."
        ),
        report_types=["threat-report", "assessment"],
        published=now,
        object_refs=[threat_actor_id] + indicator_ids,
        created_by_ref=system_id,
        labels=["geopolitical", "strategic-intelligence", threat_level.lower()],
    )
    objects.append(report)

    # ── Relationships ──
    for ind_id in indicator_ids[:10]:
        rel = Relationship(
            id=f"relationship--{uuid.uuid4()}",
            created=now,
            modified=now,
            relationship_type="indicates",
            source_ref=ind_id,
            target_ref=threat_actor_id,
            description="Signal indicates potential activity by assessed entity",
        )
        objects.append(rel)

    # ── Bundle ──
    bundle = Bundle(
        id=f"bundle--{uuid.uuid4()}",
        objects=objects,
        allow_custom=True,
    )

    return json.loads(bundle.serialize())


def _infer_domain(signal_name: str) -> str:
    """Infer the STIX domain from a signal name."""
    sn = signal_name.lower()
    if any(w in sn for w in ["military", "troop", "deployment", "exercise", "mobilization", "naval", "air"]):
        return "military"
    if any(w in sn for w in ["diplomatic", "embassy", "envoy", "summit", "treaty", "negotiation"]):
        return "diplomatic"
    if any(w in sn for w in ["economic", "sanction", "trade", "tariff", "embargo", "investment", "gdp"]):
        return "economic"
    if any(w in sn for w in ["cyber", "hack", "malware", "digital", "ddos", "ransomware"]):
        return "cyber"
    if any(w in sn for w in ["media", "propaganda", "disinformation", "narrative", "social"]):
        return "information"
    return "political"


def _generate_stix_fallback(result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate a STIX-compatible JSON structure without the stix2 library.
    Used when stix2 is not installed.
    """
    now = datetime.now(timezone.utc).isoformat()
    country = result.get("country", "UNKNOWN")
    threat_level = result.get("threat_level", "UNKNOWN")
    trace_id = result.get("trace_id", str(uuid.uuid4())[:12])
    system_id = f"identity--{uuid.uuid4()}"

    return {
        "type": "bundle",
        "id": f"bundle--{uuid.uuid4()}",
        "spec_version": "2.1",
        "objects": [
            {
                "type": "identity",
                "spec_version": "2.1",
                "id": system_id,
                "created": "2025-01-01T00:00:00.000Z",
                "modified": now,
                "name": "Politiq AI — Geopolitical Intelligence Engine",
                "identity_class": "system",
                "sectors": ["intelligence", "defense"],
            },
            {
                "type": "report",
                "spec_version": "2.1",
                "id": f"report--{uuid.uuid4()}",
                "created": now,
                "modified": now,
                "name": f"Politiq AI Assessment: {country} — {threat_level}",
                "description": (
                    f"Geopolitical intelligence assessment for {country}. "
                    f"Threat level: {threat_level}. Trace ID: {trace_id}."
                ),
                "report_types": ["threat-report", "assessment"],
                "published": now,
                "created_by_ref": system_id,
                "object_refs": [],
                "labels": ["geopolitical", threat_level.lower()],
                "external_references": [
                    {
                        "source_name": "DIP 2.0 Trace",
                        "external_id": trace_id,
                    }
                ],
                "x_dip_assessment": {
                    "country": country,
                    "threat_level": threat_level,
                    "verification_score": result.get("verification_score", 0.0),
                    "trace_id": trace_id,
                    "generator": "DIP 2.0 fallback exporter (install 'stix2' for full export)",
                },
            },
        ],
    }


# Make json available for Bundle.serialize()
import json
